add files

diff --git a/src/mysql/start_mysql b/src/mysql/start_mysql
--- a/src/mysql/start_mysql
+++ b/src/mysql/start_mysql
@@ -24,9 +24,9 @@ if [ $new_install = true ]; then
 	root_password=$(cat /dev/urandom | tr -dc _A-Z-a-z-0-9 | head -c64)
 	echo "done."
 
-	# Generate a password for the nextcloud mysql user.
-	echo -n "Generating nextcloud mysql password... "
-	nextcloud_password=$(cat /dev/urandom | tr -dc _A-Z-a-z-0-9 | head -c64)
+	# Generate a password for the pentaho mysql user.
+	echo -n "Generating pentaho mysql password... "
+	pentaho_password=$(cat /dev/urandom | tr -dc _A-Z-a-z-0-9 | head -c64)
 	echo "done."
 
 	# Save root user information
@@ -37,15 +37,15 @@ if [ $new_install = true ]; then
 
 	# Now set everything up in one step:
 	# 1) Set the root user's password
-	# 2) Create the nextcloud user
-	# 3) Create the nextcloud database
-	# 4) Grant the nextcloud user privileges on the nextcloud database
-	echo -n "Setting up users and nextcloud database... "
+	# 2) Create the pentaho user
+	# 3) Create the pentaho database
+	# 4) Grant the pentaho user privileges on the pentaho database
+	echo -n "Setting up users and pentaho database... "
 	mysql --defaults-file=$root_option_file <<SQL
 ALTER USER 'root'@'localhost' IDENTIFIED BY '$root_password';
-CREATE USER 'nextcloud'@'localhost' IDENTIFIED BY '$nextcloud_password';
-CREATE DATABASE nextcloud;
-GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'localhost' IDENTIFIED BY '$nextcloud_password';
+CREATE USER 'pentaho'@'localhost' IDENTIFIED BY '$pentaho_password';
+CREATE DATABASE pentaho;
+GRANT ALL PRIVILEGES ON pentaho.* TO 'pentaho'@'localhost' IDENTIFIED BY '$pentaho_password';
 SQL
 	if [ $? -eq 0 ]; then
 		echo "done."
@@ -54,6 +54,63 @@ SQL
 		$SNAP/support-files/mysql.server stop
 		rm -rf $SNAP_DATA/mysql/*
 	fi
+
+	echo -n "Setting up users and pentaho repository database... "
+	mysql --defaults-file=$root_option_file <<SQL
+ALTER USER 'root'@'localhost' IDENTIFIED BY '$root_password';
+CREATE USER 'jcr_user'@'localhost' IDENTIFIED BY '$pentaho_password';
+CREATE DATABASE jackrabbit;
+GRANT ALL PRIVILEGES ON jackrabbit.* TO 'jcr_user'@'localhost' IDENTIFIED BY '$pentaho_password';
+SQL
+	if [ $? -eq 0 ]; then
+		echo "done."
+	else
+		echo "Failed to initialize-- reverting..."
+		$SNAP/support-files/mysql.server stop
+		rm -rf $SNAP_DATA/mysql/*
+	fi
+
+	echo -n "Setting up users and pentaho quartz database... "
+	mysql --defaults-file=$root_option_file <<SQL
+ALTER USER 'root'@'localhost' IDENTIFIED BY '$root_password';
+CREATE USER 'hibuser'@'localhost' IDENTIFIED BY '$pentaho_password';
+CREATE DATABASE hibernate;
+GRANT ALL PRIVILEGES ON hibernate.* TO 'hibuser'@'localhost' IDENTIFIED BY '$pentaho_password';
+SQL
+	if [ $? -eq 0 ]; then
+		echo "done."
+	else
+		echo "Failed to initialize-- reverting..."
+		$SNAP/support-files/mysql.server stop
+		rm -rf $SNAP_DATA/mysql/*
+	fi
+
+	echo -n "Setting up users and pentaho quartz database... "
+	mysql --defaults-file=$root_option_file <<SQL
+ALTER USER 'root'@'localhost' IDENTIFIED BY '$root_password';
+CREATE USER 'pentaho_user'@'localhost' IDENTIFIED BY '$pentaho_password';
+CREATE DATABASE quartz;
+GRANT ALL PRIVILEGES ON quartz.* TO 'pentaho_user'@'localhost' IDENTIFIED BY '$pentaho_password';
+SQL
+	if [ $? -eq 0 ]; then
+		echo "done."
+	else
+		echo "Failed to initialize-- reverting..."
+		$SNAP/support-files/mysql.server stop
+		rm -rf $SNAP_DATA/mysql/*
+	fi
+
+	echo -n "Setting up users and pentaho jcr database... "
+	mysql --defaults-file=$root_option_file < $SNAP/support-files/create_quartz_mysql.sql
+	if [ $? -eq 0 ]; then
+		echo "done."
+	else
+		echo "Failed to initialize-- reverting..."
+		$SNAP/support-files/mysql.server stop
+		rm -rf $SNAP_DATA/mysql/*
+	fi
+
+
 
 	# Now the root mysql user has a password. Save that as well.
 	echo "password=$root_password" >> $root_option_file
@@ -80,10 +137,10 @@ if [ $? -eq 0 ]; then
 fi
 
 # If this was a new installation, wait until the server is all up and running
-# before saving off the nextcloud user's password. This way the presence of the
+# before saving off the pentaho user's password. This way the presence of the
 # file can be used as a signal that mysql is ready to be used.
 if [ $new_install = true ]; then
-	mysql_set_nextcloud_password "$nextcloud_password"
+	mysql_set_pentaho_password "$pentaho_password"
 fi
 
 # Wait here until mysql exits (turn a forking service into simple). This is
